### ISSUE TITLE
Support ROS2

### ISSUE THREAD

**Issue by Ericsii** [hku-mars/FAST_LIO#234] opened 2023-04-06 07:28 UTC
Is any plan to support ROS2? I'm porting FAST_LIO into ROS2-humble. Wondering if you have a plan to support ROS2. If so could you please create a new branch `ros2`? I'll take a few PRs to port my ros2 code to this branch

**Comment by Ecstasy-EC** [comment] 2023-04-08 08:06
Absolutely yes! Our team has been busy these days. We will create the branch for you in the coming week.

**Comment by Ericsii** [comment] 2023-04-09 03:58
Very appreciate. I made a simple port of FAST_LIO to ros2 version. Please feel free to check it on my fork. https://github.com/Ericsii/FAST_LIO

**Comment by Ecstasy-EC** [comment] 2023-04-10 06:50
> Very appreciate. I made a simple port of FAST_LIO to ros2 version. Please feel free to check it on my fork. https://github.com/Ericsii/FAST_LIO

Thanks! We will reach you as soon as we finish the test.

**Comment by Ecstasy-EC** [comment] 2023-04-20 13:44
@Ericsii   Could you please provide me with your email for communicating more efficiently about some problems I met when testing your branch?

**Comment by TheodorPatrickZ** [comment] 2023-05-17 08:53
> Very appreciate. I made a simple port of FAST_LIO to ros2 version. Please feel free to check it on my fork. [https://github.com/Ericsii/FAST_LIO ](https://github.com/Ericsii/FAST_LIO)

Hi are you able to run the provided rosbags when convertet to ros2?
It is not working for me.

**Comment by Ecstasy-EC** [comment] 2023-05-17 09:00
> > Very appreciate. I made a simple port of FAST_LIO to ros2 version. Please feel free to check it on my fork. [https://github.com/Ericsii/FAST_LIO ](https://github.com/Ericsii/FAST_LIO)
> 
> Hi are you able to run the provided rosbags when convertet to ros2? It is not working for me.

Hi. I also tried this repo but I could not run successfully yet. I was trying to contact the author but got no response.

**Comment by Ericsii** [comment] 2023-05-19 11:54
@Ecstasy-EC Sorry for the late reply. Here is my email ericfengx@foxmail.com.

**Comment by Ericsii** [comment] 2023-05-19 11:57
> > Very appreciate. I made a simple port of FAST_LIO to ros2 version. Please feel free to check it on my fork. [https://github.com/Ericsii/FAST_LIO ](https://github.com/Ericsii/FAST_LIO)
> 
> Hi are you able to run the provided rosbags when convertet to ros2? It is not working for me.

rosbags for ros1 is not compatible in ros2. You can follow this tutorial to convert rosbags to ros2. https://ternaris.gitlab.io/rosbags/topics/convert.html

**Comment by Ericsii** [comment] 2023-05-22 16:36
@Ecstasy-EC Can you reopen this issue? So that others can communicate about ros2 migration.

**Comment by Ecstasy-EC** [comment] 2023-05-23 07:10
> @Ecstasy-EC Can you reopen this issue? So that others can communicate about ros2 migration.

Reopened.

**Comment by andy-zhuo-02** [comment] 2023-05-25 14:22
I'm also interested in the ROS2 version of FAST-LIO. Is there a stable version yet?

**Comment by andy-zhuo-02** [comment] 2023-05-25 14:52
I have successfully run through the data stream, but there seems to be a problem with the results of the mapping. The appearance of point clouds is very strange. The range of point clouds is very small and their positioning is easy to drift. I don't know if there are any suggestions.
![01](https://github.com/hku-mars/FAST_LIO/assets/121604666/7532f7c5-3310-41a0-b83c-41769b446c6e)
![02](https://github.com/hku-mars/FAST_LIO/assets/121604666/b911982e-54c6-48ed-a7de-994e93edcb29)

**Comment by andy-zhuo-02** [comment] 2023-05-26 11:41
> > I have successfully run through the data stream, but there seems to be a problem with the results of the mapping. The appearance of point clouds is very strange. The range of point clouds is very small and their positioning is easy to drift. I don't know if there are any suggestions. ![01](https://user-images.githubusercontent.com/121604666/240951564-7532f7c5-3310-41a0-b83c-41769b446c6e.png) ![02](https://user-images.githubusercontent.com/121604666/240951603-b911982e-54c6-48ed-a7de-994e93edcb29.png)
> 
> Are you able to run FAST-LIO2 in ros1 using the same config on the data?

It seems that, YES.

here is the fast-lio in ROS noetic. I compared all config in mid70.yaml, or I missed something?

![2023-05-26 19-39-09 的屏幕截图](https://github.com/hku-mars/FAST_LIO/assets/121604666/0066497d-5dbd-40aa-9e2f-6c83d1659256)

**Comment by Ecstasy-EC** [comment] 2023-05-26 14:01
@Ericsii  Would you please provide some help if you have any ideas?

**Comment by Ericsii** [comment] 2023-05-30 08:48
> > I have successfully run through the data stream, but there seems to be a problem with the results of the mapping. The appearance of point clouds is very strange. The range of point clouds is very small and their positioning is easy to drift. I don't know if there are any suggestions. ![01](https://user-images.githubusercontent.com/121604666/240951564-7532f7c5-3310-41a0-b83c-41769b446c6e.png) ![02](https://user-images.githubusercontent.com/121604666/240951603-b911982e-54c6-48ed-a7de-994e93edcb29.png)
> 
> Are you able to run FAST-LIO2 in ros1 using the same config on the data?

Can you give me your configuration file? This may be because `publish.dense_publish_en` is set to `false`.

**Comment by Ericsii** [comment] 2023-06-23 05:37
Please keep this issue open.

**Comment by Taeyoung96** [comment] 2023-07-26 08:33
@Ecstasy-EC @Ericsii   

I got the FAST-LIO2 ros2 version up and running in docker based on the ros2 branch created by Ericsii and it works pretty well!  

The dockerized repository is shown below. 
I even added a function to save the trajectory and 3D map.

After converting the M2DGR dataset to a ros2 bagfile, I performed experiments using the velodyne and handsfree imu.

See below for more details,
https://github.com/Taeyoung96/FAST_LIO_ROS2/tree/ros2

![Result](https://github.com/hku-mars/FAST_LIO/assets/41863759/226304b1-7231-4dbe-8b16-3157f1d42f0c)

**Comment by ryanpdoc57** [comment] 2023-11-02 15:18
Hello! I was able to successfully fun ROS2 version of fast-lio in Humble, but am having issues building the package using ROS2 foxy. Has anyone else experienced this?

**Comment by ryanpdoc57** [comment] 2023-11-02 15:21
@Ericsii Hello! I was able to successfully fun ROS2 version of fast-lio in Humble, but am having issues building the package using ROS2 foxy. Have you tested this in foxy? If so did you run into any build issues? It is specifically with a service and a service callback from the lasermapping.cpp file.

**Comment by Ericsii** [comment] 2023-11-24 15:14
> @Ericsii Hello! I was able to successfully run ROS2 version of fast-lio in Humble, but am having issues building the package using ROS2 foxy. Have you tested this in foxy? If so did you run into any build issues? It is specifically with a service and a service callback from the lasermapping.cpp file.

Sorry, I didn't test this on ROS Foxy. Can you provide a build log on foxy?

**Comment by Ericsii** [comment] 2023-11-24 15:36
@Ecstasy-EC Perhaps we can now create a new branch for ROS2?

**Comment by wyb17js** [comment] 2023-12-21 01:41
Hello, we use this transplanted fast-lio2 algorithm to realize the robot's positioning function on humble, but we encounter a problem: the positioning is lost after a period of time. We find that: the time that the positioning can be maintained is related to the radar release frequency, the higher the frequency, the longer the duration; With the operation of the program, there will be an interval in the use of radar data. For example, I am publishing a point cloud at a frequency of 10HZ. Originally, my radar data is matched with imu data every 0.1s and used by the algorithm, but with the operation of the program, my radar data may be used at an interval of 0.2s and 0.3s, and this interval gradually increases. When the interval reaches 1s, the location is lost. I was wondering if you had the same problem.Do you have any good suggestions on this matter？
I'm looking forward to your reply.

**Comment by Ericsii** [comment] 2023-12-21 04:04
> For example, I am publishing a point cloud at a frequency of 10HZ. Originally, my radar data is matched with imu data every 0.1s and used by the algorithm, but with the operation of the program, my radar data may be used at an interval of 0.2s and 0.3s, and this interval gradually increases. When the interval reaches 1s, the location is lost.

@wyb17js have you tested this on the original version of FAST_LIO for ROS1? If the result is the same, you may check whether the timestamps of IMU and lidar are aligned.

**Comment by wyb17js** [comment] 2023-12-21 05:46
Not yet, but I have tested it in a simulation environment, using radar and imu plugins, and there is also a loss of location, but the location lasts longer than it actually does. So how do I align the radar and imu timestamps? The radar I use is mid360, no external imu

**Comment by Ericsii** [comment] 2023-12-21 06:05
> I have tested it in a simulation environment

Which simulator did you use? I have tested on Gazebo the lidar output frequency is not usable for common SLAM algorithms. Please use real environment

**Comment by wyb17js** [comment] 2023-12-21 06:08
> > I have tested it in a simulation environment
> 
> Which simulator did you use? I have tested on Gazebo the lidar output frequency is not usable for common SLAM algorithms. Please use real environment

I use Gazebo,too. Does time synchronization refer to hardware synchronization? I noticed that there is code in the program to handle timestamp deviation, and it takes effect when time_sync_en is turned on. I tried this feature but it didn't work well.

**Comment by Ericsii** [comment] 2023-12-22 05:57
> > > I have tested it in a simulation environment
> > 
> > 
> > Which simulator did you use? I have tested on Gazebo the lidar output frequency is not usable for common SLAM algorithms. Please use real environment
> 
> I use Gazebo,too. Does time synchronization refer to hardware synchronization? I noticed that there is code in the program to handle timestamp deviation, and it takes effect when time_sync_en is turned on. I tried this feature but it didn't work well.

Please test it in a real-world environment. The online time synchronization algorithm only estimates the fixed timestamp offset between lidar and IMU. For dynamic time offset, it may not work as expected

**Comment by wyb17js** [comment] 2023-12-22 06:48
> > > > I have tested it in a simulation environment
> > > 
> > > 
> > > Which simulator did you use? I have tested on Gazebo the lidar output frequency is not usable for common SLAM algorithms. Please use real environment
> > 
> > 
> > I use Gazebo,too. Does time synchronization refer to hardware synchronization? I noticed that there is code in the program to handle timestamp deviation, and it takes effect when time_sync_en is turned on. I tried this feature but it didn't work well.
> 
> Please test it in a real-world environment. The online time synchronization algorithm only estimates the fixed timestamp offset between lidar and IMU. For dynamic time offset, it may not work as expected

So how do I deal with dynamic time offset? I don't know much about it. Could you give me some advice?

**Comment by Ericsii** [comment] 2023-12-28 05:36
> So how do I deal with dynamic time offset? I don't know much about it. Could you give me some advice?

Sorry, I'm not an expert in timestamp calibration. You can search for some academic papers in these related fields.

**Comment by Ecstasy-EC** [comment] 2024-02-25 12:30
The issue is closed. A new branch for ROS2 has been created and the pull request from @Ericsii is merged. Please open new issues if any other problems are found in the ROS2 version.

**Closed by Ecstasy-EC** 2024-02-25 12:30 UTC
Labels: enhancement

**Comment by lingxe01** [comment] 2024-07-15 01:46
Have you tested it on ros version foxy? I got an error when compiling.
`/opt/ros/foxy/include/rclcpp/create_service.hpp:43:3: error: no matching function for call to ‘rclcpp::AnyServiceCallback<std_srvs::srv::Trigger>::set(std::_Bind<void (LaserMappingNode::*(LaserMappingNode*, std::_Placeholder<1>, std::_Placeholder<2>))(std::shared_ptr<const std_srvs::srv::Trigger_Request_<std::allocator<void> > >, std::shared_ptr<std_srvs::srv::Trigger_Response_<std::allocator<void> > >)>)’
   43 |   any_service_callback.set(std::forward<CallbackT>(callback));`

**Comment by wendwosenbb** [comment] 2024-07-23 06:02
faced same issue on ros2 galactic.

**Comment by wendwosenbb** [comment] 2024-07-23 07:14
looks like a third place holder is required for the service request header/id. 
changing line 945 of lasermapping.cpp to
`        map_save_srv_ = this->create_service<std_srvs::srv::Trigger>("map_save", std::bind(&LaserMappingNode::map_save_callback, this, std::placeholders::_1, std::placeholders::_2, std::placeholders::_3));`

and line 1115 to
`    void map_save_callback(  const std::shared_ptr<rmw_request_id_t> request_header,
  const std::shared_ptr<std_srvs::srv::Trigger::Request> req,
  const std::shared_ptr<std_srvs::srv::Trigger::Response> res)`
  
 solved the error
 `/opt/ros/galactic/include/rclcpp/create_service.hpp:43:3: error: no matching function for call to ‘rclcpp::AnyServiceCallback<std_srvs::srv::Trigger>::set(std::_Bind<void (LaserMappingNode::*(LaserMappingNode*, std::_Placeholder<1>, std::_Placeholder<2>))(std::shared_ptr<const std_srvs::srv::Trigger_Request_<std::allocator<void> > >, std::shared_ptr<std_srvs::srv::Trigger_Response_<std::allocator<void> > >)>)’ 43 |   any_service_callback.set(std::forward<CallbackT>(callback));`

**Comment by Ericsii** [comment] 2024-07-23 07:16
> Have you tested it on ros version foxy? I got an error when compiling. `/opt/ros/foxy/include/rclcpp/create_service.hpp:43:3: error: no matching function for call to ‘rclcpp::AnyServiceCallback<std_srvs::srv::Trigger>::set(std::_Bind<void (LaserMappingNode::*(LaserMappingNode*, std::_Placeholder<1>, std::_Placeholder<2>))(std::shared_ptr<const std_srvs::srv::Trigger_Request_<std::allocator<void> > >, std::shared_ptr<std_srvs::srv::Trigger_Response_<std::allocator<void> > >)>)’ 43 | any_service_callback.set(std::forward<CallbackT>(callback));`

You can use this fork's version it solve this problem in foxy https://github.com/hku-mars/FAST_LIO/pull/334
